<a href="https://colab.research.google.com/github/felipecacique/Pytorch-Tutorial-Youtube/blob/main/Copy_of_Intro_To_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

In [ ]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 0.2561,  0.1648,  1.4153, -0.7325],
        [ 2.3608, -0.3193,  0.3564,  0.5650],
        [-0.1631,  0.6790,  0.4446, -0.5954]])

In [ ]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Reshape and view
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
# Reshape if dont lnow the number of items using -1
my_torch2 = torch.arange(10)
my_torch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_torch2 = my_torch2.reshape(2,-1)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_torch4 = my_torch3.view(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
# with reshape and view, they will update
my_torch4[1][1] = 1991
my_torch4

tensor([[   0,    1,    2,    3,    4],
        [   5, 1991,    7, 1991, 1991]])

In [ ]:
my_torch3

tensor([   0,    1,    2,    3,    4,    5, 1991,    7, 1991, 1991])

In [ ]:
my_torch3[3]

tensor(3)

In [ ]:
# Grab a slice
my_torch8 = torch.arange(10)
my_torch8 = my_torch8.reshape(5,2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [ ]:
my_torch8[:,1]

tensor([1, 3, 5, 7, 9])

In [ ]:
my_torch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

Tensor Math operations

In [ ]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [ ]:
# addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [ ]:
# addition longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [ ]:
# subtraction
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [ ]:
# sub function
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [ ]:
# multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [ ]:
# mul longhand
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [ ]:
# division
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [ ]:
# div longhand
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [ ]:
# remainder
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [ ]:
#  remainder longhand
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [ ]:
# exponents / power
torch.pow(tensor_a,tensor_b)

tensor([    1,    64,  2187, 65536])

In [ ]:
tensor_a ** tensor_b

tensor([    1,    64,  2187, 65536])

In [ ]:
# another way to write longhand
tensor_a.add(tensor_b) # notice that the sum is not reasigned to the varaible tensor_a
tensor_a

tensor([ 66,  80,  94, 108])

In [ ]:
# reassignment
tensor_a = tensor_a + tensor_b
tensor_a

tensor([41, 50, 59, 68])

In [ ]:
# tensor_a = tensor_a + tensor_b
tensor_a.add_(tensor_b) # the underline after add reasigns the sum to the variable tensor_a
tensor_a

tensor([ 66,  80,  94, 108])